// Podmin <https://podmin.dev>
// Copyright The Podmin Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/coordination.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coordination_Sync_FullMethodName = "/podmin.agent.api.v1.Coordination/Sync"
)

// CoordinationClient is the client API for Coordination service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Coordination synchronizes node state and complete Service snapshots with the elected leader.
type CoordinationClient interface {
	// Sync maintains one bidirectional coordination session between a follower node and the leader node.
	Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type coordinationClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationClient(cc grpc.ClientConnInterface) CoordinationClient {
	return &coordinationClient{cc}
}

func (c *coordinationClient) Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Coordination_ServiceDesc.Streams[0], Coordination_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordination_SyncClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// CoordinationServer is the server API for Coordination service.
// All implementations must embed UnimplementedCoordinationServer
// for forward compatibility.
//
// Coordination synchronizes node state and complete Service snapshots with the elected leader.
type CoordinationServer interface {
	// Sync maintains one bidirectional coordination session between a follower node and the leader node.
	Sync(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedCoordinationServer()
}

// UnimplementedCoordinationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinationServer struct{}

func (UnimplementedCoordinationServer) Sync(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedCoordinationServer) mustEmbedUnimplementedCoordinationServer() {}
func (UnimplementedCoordinationServer) testEmbeddedByValue()                      {}

// UnsafeCoordinationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationServer will
// result in compilation errors.
type UnsafeCoordinationServer interface {
	mustEmbedUnimplementedCoordinationServer()
}

func RegisterCoordinationServer(s grpc.ServiceRegistrar, srv CoordinationServer) {
	// If the following call panics, it indicates UnimplementedCoordinationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coordination_ServiceDesc, srv)
}

func _Coordination_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinationServer).Sync(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordination_SyncServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// Coordination_ServiceDesc is the grpc.ServiceDesc for Coordination service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordination_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "podmin.agent.api.v1.Coordination",
	HandlerType: (*CoordinationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _Coordination_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/coordination.proto",
}
