// Podmin <https://podmin.dev>
// Copyright The Podmin Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v5.29.3
// source: proto/coordination.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientMessage carries one node-to-leader coordination event.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_NodeState
	//	*ClientMessage_Drain
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_coordination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientMessage) GetNodeState() *NodeState {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_NodeState); ok {
			return x.NodeState
		}
	}
	return nil
}

func (x *ClientMessage) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_NodeState struct {
	NodeState *NodeState `protobuf:"bytes,2,opt,name=node_state,json=nodeState,proto3,oneof"`
}

type ClientMessage_Drain struct {
	Drain *Drain `protobuf:"bytes,3,opt,name=drain,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Message() {}

func (*ClientMessage_NodeState) isClientMessage_Message() {}

func (*ClientMessage_Drain) isClientMessage_Message() {}

// Hello identifies a node session and declares its complete Service contract and IPv6 prefix.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Cluster       string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	NodeGroup     string                 `protobuf:"bytes,3,opt,name=node_group,json=nodeGroup,proto3" json:"node_group,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConfigDigest  string                 `protobuf:"bytes,5,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	Services      []*Service             `protobuf:"bytes,6,rep,name=services,proto3" json:"services,omitempty"`
	Ipv6Prefix    string                 `protobuf:"bytes,7,opt,name=ipv6_prefix,json=ipv6Prefix,proto3" json:"ipv6_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_coordination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Hello) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Hello) GetNodeGroup() string {
	if x != nil {
		return x.NodeGroup
	}
	return ""
}

func (x *Hello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Hello) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

func (x *Hello) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Hello) GetIpv6Prefix() string {
	if x != nil {
		return x.Ipv6Prefix
	}
	return ""
}

// Service describes one desired Service and its optional ready backends.
type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fqdn          string                 `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Vip           string                 `protobuf:"bytes,3,opt,name=vip,proto3" json:"vip,omitempty"`
	Ports         []*TargetPort          `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	Backends      []*Endpoint            `protobuf:"bytes,5,rep,name=backends,proto3" json:"backends,omitempty"`
	NodeGroup     string                 `protobuf:"bytes,6,opt,name=node_group,json=nodeGroup,proto3" json:"node_group,omitempty"`
	Namespace     string                 `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_proto_coordination_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *Service) GetVip() string {
	if x != nil {
		return x.Vip
	}
	return ""
}

func (x *Service) GetPorts() []*TargetPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Service) GetBackends() []*Endpoint {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *Service) GetNodeGroup() string {
	if x != nil {
		return x.NodeGroup
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// TargetPort maps one Service port to the corresponding Pod port.
type TargetPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ServicePort   uint32                 `protobuf:"varint,3,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,4,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetPort) Reset() {
	*x = TargetPort{}
	mi := &file_proto_coordination_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetPort) ProtoMessage() {}

func (x *TargetPort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetPort.ProtoReflect.Descriptor instead.
func (*TargetPort) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{3}
}

func (x *TargetPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TargetPort) GetServicePort() uint32 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

func (x *TargetPort) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

// Endpoint describes one ready Pod backend for a Service.
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	PodUid        string                 `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Ports         []*TargetPort          `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	NodeGroup     string                 `protobuf:"bytes,5,opt,name=node_group,json=nodeGroup,proto3" json:"node_group,omitempty"`
	Namespace     string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_proto_coordination_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{4}
}

func (x *Endpoint) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Endpoint) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *Endpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Endpoint) GetPorts() []*TargetPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Endpoint) GetNodeGroup() string {
	if x != nil {
		return x.NodeGroup
	}
	return ""
}

func (x *Endpoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// NodeState replaces a node session's complete set of ready endpoints.
type NodeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ConfigDigest  string                 `protobuf:"bytes,3,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_proto_coordination_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{5}
}

func (x *NodeState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NodeState) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *NodeState) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

func (x *NodeState) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// Drain asks the leader to withdraw a terminating node session immediately.
type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_proto_coordination_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{6}
}

func (x *Drain) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ServerMessage carries one leader-to-node acknowledgement or complete snapshot.
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Ack
	//	*ServerMessage_Snapshot
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_coordination_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ServerMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

func (*ServerMessage_Ack) isServerMessage_Message() {}

func (*ServerMessage_Snapshot) isServerMessage_Message() {}

// Ack confirms that the leader accepted a NodeState sequence.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_coordination_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Snapshot contains the complete generation and revision of cluster Service state.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	LeaderId      string                 `protobuf:"bytes,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	ConfigDigest  string                 `protobuf:"bytes,4,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	Services      []*Service             `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_coordination_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coordination_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_coordination_proto_rawDescGZIP(), []int{9}
}

func (x *Snapshot) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Snapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Snapshot) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *Snapshot) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

func (x *Snapshot) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_proto_coordination_proto protoreflect.FileDescriptor

const file_proto_coordination_proto_rawDesc = "" +
	"\n" +
	"\x18proto/coordination.proto\x12\x13podmin.agent.api.v1\"\xc3\x01\n" +
	"\rClientMessage\x122\n" +
	"\x05hello\x18\x01 \x01(\v2\x1a.podmin.agent.api.v1.HelloH\x00R\x05hello\x12?\n" +
	"\n" +
	"node_state\x18\x02 \x01(\v2\x1e.podmin.agent.api.v1.NodeStateH\x00R\tnodeState\x122\n" +
	"\x05drain\x18\x03 \x01(\v2\x1a.podmin.agent.api.v1.DrainH\x00R\x05drainB\t\n" +
	"\amessage\"\xf8\x01\n" +
	"\x05Hello\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1d\n" +
	"\n" +
	"node_group\x18\x03 \x01(\tR\tnodeGroup\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12#\n" +
	"\rconfig_digest\x18\x05 \x01(\tR\fconfigDigest\x128\n" +
	"\bservices\x18\x06 \x03(\v2\x1c.podmin.agent.api.v1.ServiceR\bservices\x12\x1f\n" +
	"\vipv6_prefix\x18\a \x01(\tR\n" +
	"ipv6Prefix\"\xf2\x01\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04fqdn\x18\x02 \x01(\tR\x04fqdn\x12\x10\n" +
	"\x03vip\x18\x03 \x01(\tR\x03vip\x125\n" +
	"\x05ports\x18\x04 \x03(\v2\x1f.podmin.agent.api.v1.TargetPortR\x05ports\x129\n" +
	"\bbackends\x18\x05 \x03(\v2\x1d.podmin.agent.api.v1.EndpointR\bbackends\x12\x1d\n" +
	"\n" +
	"node_group\x18\x06 \x01(\tR\tnodeGroup\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\"\x80\x01\n" +
	"\n" +
	"TargetPort\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12!\n" +
	"\fservice_port\x18\x03 \x01(\rR\vservicePort\x12\x1f\n" +
	"\vtarget_port\x18\x04 \x01(\rR\n" +
	"targetPort\"\xcb\x01\n" +
	"\bEndpoint\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x125\n" +
	"\x05ports\x18\x04 \x03(\v2\x1f.podmin.agent.api.v1.TargetPortR\x05ports\x12\x1d\n" +
	"\n" +
	"node_group\x18\x05 \x01(\tR\tnodeGroup\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\"\xa8\x01\n" +
	"\tNodeState\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12#\n" +
	"\rconfig_digest\x18\x03 \x01(\tR\fconfigDigest\x12;\n" +
	"\tendpoints\x18\x04 \x03(\v2\x1d.podmin.agent.api.v1.EndpointR\tendpoints\"&\n" +
	"\x05Drain\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x85\x01\n" +
	"\rServerMessage\x12,\n" +
	"\x03ack\x18\x01 \x01(\v2\x18.podmin.agent.api.v1.AckH\x00R\x03ack\x12;\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1d.podmin.agent.api.v1.SnapshotH\x00R\bsnapshotB\t\n" +
	"\amessage\"!\n" +
	"\x03Ack\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"\xc2\x01\n" +
	"\bSnapshot\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x1b\n" +
	"\tleader_id\x18\x03 \x01(\tR\bleaderId\x12#\n" +
	"\rconfig_digest\x18\x04 \x01(\tR\fconfigDigest\x128\n" +
	"\bservices\x18\x05 \x03(\v2\x1c.podmin.agent.api.v1.ServiceR\bservices2b\n" +
	"\fCoordination\x12R\n" +
	"\x04Sync\x12\".podmin.agent.api.v1.ClientMessage\x1a\".podmin.agent.api.v1.ServerMessage(\x010\x01B5Z3github.com/podmin-dev/podmin/internal/agent/api;apib\x06proto3"

var (
	file_proto_coordination_proto_rawDescOnce sync.Once
	file_proto_coordination_proto_rawDescData []byte
)

func file_proto_coordination_proto_rawDescGZIP() []byte {
	file_proto_coordination_proto_rawDescOnce.Do(func() {
		file_proto_coordination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coordination_proto_rawDesc), len(file_proto_coordination_proto_rawDesc)))
	})
	return file_proto_coordination_proto_rawDescData
}

var file_proto_coordination_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_coordination_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: podmin.agent.api.v1.ClientMessage
	(*Hello)(nil),         // 1: podmin.agent.api.v1.Hello
	(*Service)(nil),       // 2: podmin.agent.api.v1.Service
	(*TargetPort)(nil),    // 3: podmin.agent.api.v1.TargetPort
	(*Endpoint)(nil),      // 4: podmin.agent.api.v1.Endpoint
	(*NodeState)(nil),     // 5: podmin.agent.api.v1.NodeState
	(*Drain)(nil),         // 6: podmin.agent.api.v1.Drain
	(*ServerMessage)(nil), // 7: podmin.agent.api.v1.ServerMessage
	(*Ack)(nil),           // 8: podmin.agent.api.v1.Ack
	(*Snapshot)(nil),      // 9: podmin.agent.api.v1.Snapshot
}
var file_proto_coordination_proto_depIdxs = []int32{
	1,  // 0: podmin.agent.api.v1.ClientMessage.hello:type_name -> podmin.agent.api.v1.Hello
	5,  // 1: podmin.agent.api.v1.ClientMessage.node_state:type_name -> podmin.agent.api.v1.NodeState
	6,  // 2: podmin.agent.api.v1.ClientMessage.drain:type_name -> podmin.agent.api.v1.Drain
	2,  // 3: podmin.agent.api.v1.Hello.services:type_name -> podmin.agent.api.v1.Service
	3,  // 4: podmin.agent.api.v1.Service.ports:type_name -> podmin.agent.api.v1.TargetPort
	4,  // 5: podmin.agent.api.v1.Service.backends:type_name -> podmin.agent.api.v1.Endpoint
	3,  // 6: podmin.agent.api.v1.Endpoint.ports:type_name -> podmin.agent.api.v1.TargetPort
	4,  // 7: podmin.agent.api.v1.NodeState.endpoints:type_name -> podmin.agent.api.v1.Endpoint
	8,  // 8: podmin.agent.api.v1.ServerMessage.ack:type_name -> podmin.agent.api.v1.Ack
	9,  // 9: podmin.agent.api.v1.ServerMessage.snapshot:type_name -> podmin.agent.api.v1.Snapshot
	2,  // 10: podmin.agent.api.v1.Snapshot.services:type_name -> podmin.agent.api.v1.Service
	0,  // 11: podmin.agent.api.v1.Coordination.Sync:input_type -> podmin.agent.api.v1.ClientMessage
	7,  // 12: podmin.agent.api.v1.Coordination.Sync:output_type -> podmin.agent.api.v1.ServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_coordination_proto_init() }
func file_proto_coordination_proto_init() {
	if File_proto_coordination_proto != nil {
		return
	}
	file_proto_coordination_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_NodeState)(nil),
		(*ClientMessage_Drain)(nil),
	}
	file_proto_coordination_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coordination_proto_rawDesc), len(file_proto_coordination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coordination_proto_goTypes,
		DependencyIndexes: file_proto_coordination_proto_depIdxs,
		MessageInfos:      file_proto_coordination_proto_msgTypes,
	}.Build()
	File_proto_coordination_proto = out.File
	file_proto_coordination_proto_goTypes = nil
	file_proto_coordination_proto_depIdxs = nil
}
