// Podmin <https://podmin.dev>
// Copyright The Podmin Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfBackendValue struct {
	_       structs.HostLayout
	Address [16]uint8
	Port    uint16
	Pad     uint16
}

type bpfFlowKey struct {
	_               structs.HostLayout
	Source          [16]uint8
	Destination     [16]uint8
	SourcePort      uint16
	DestinationPort uint16
	Protocol        uint8
	Pad             [3]uint8
}

type bpfForwardValue struct {
	_           structs.HostLayout
	Backend     [16]uint8
	BackendPort uint16
	SnatPort    uint16
}

type bpfReverseValue struct {
	_          structs.HostLayout
	Client     [16]uint8
	Vip        [16]uint8
	ClientPort uint16
	VipPort    uint16
}

type bpfServiceKey struct {
	_        structs.HostLayout
	Vip      [16]uint8
	Port     uint16
	Protocol uint8
	Pad      uint8
}

type bpfServiceValue struct {
	_             structs.HostLayout
	BackendOffset uint32
	BackendCount  uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapBackends       = "backends"
	bpfMapConfig         = "config"
	bpfMapForwardFlows   = "forward_flows"
	bpfMapReverseFlows   = "reverse_flows"
	bpfMapServiceVips    = "service_vips"
	bpfMapServices       = "services"
	bpfProgPodminIngress = "podmin_ingress"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	PodminIngress *ebpf.ProgramSpec `ebpf:"podmin_ingress"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Backends     *ebpf.MapSpec `ebpf:"backends"`
	Config       *ebpf.MapSpec `ebpf:"config"`
	ForwardFlows *ebpf.MapSpec `ebpf:"forward_flows"`
	ReverseFlows *ebpf.MapSpec `ebpf:"reverse_flows"`
	ServiceVips  *ebpf.MapSpec `ebpf:"service_vips"`
	Services     *ebpf.MapSpec `ebpf:"services"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Backends     *ebpf.Map `ebpf:"backends"`
	Config       *ebpf.Map `ebpf:"config"`
	ForwardFlows *ebpf.Map `ebpf:"forward_flows"`
	ReverseFlows *ebpf.Map `ebpf:"reverse_flows"`
	ServiceVips  *ebpf.Map `ebpf:"service_vips"`
	Services     *ebpf.Map `ebpf:"services"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Backends,
		m.Config,
		m.ForwardFlows,
		m.ReverseFlows,
		m.ServiceVips,
		m.Services,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	PodminIngress *ebpf.Program `ebpf:"podmin_ingress"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.PodminIngress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
